### ISSUE TITLE
License unclear.

### ISSUE THREAD

**Issue by n2liquid** [munificent/game-programming-patterns#281]
Hello. It's clear that the book's source-code is made available gratis here on GitHub, but what is its license, exactly? What am I allowed to do with this source-code, besides read it? If I make modifications to it, am I allowed to publish on my own website? Am I allowed to publish a PDF of your book I prepared myself, or of modified copies?

Please specify a license on the project root. Free documentation licenses are contracts upon which communities can build, deprecating trust. Have you considered the GFDL or something else?

I could help you choose a license, if you want.

**Comment by n2liquid** [comment]
No updates? :( This project has been forked 165 times. Are you okay with that?

**Comment by munificent** [comment]
Sorry, I have been super distracted by other stuff since I finished writing the book.

Yes, I know I need to be clearer here. I just haven't spent the time to read up on a bunch of licenses and pick the correct one. In general, I'm fine with people forking the book and poking around in the source. I am incredibly grateful when they send my patches.

I'm happy if people do things like create PDFs or eBooks for their own use, but would prefer if they didn't publish any of those and public consumption. Likewise, I'd rather not have multiple slightly different versions of the website floating around online, since I think it is likely to just confuse readers.

**Comment by Gheoan** [comment]
It would be great if a license is specified. The code that handles the positioning of the `aside` elements is valuable and it is a shame it cannot be reused.

**Comment by tchalvak** [comment]
Github has simplified the choosing process:
https://github.com/blog/1530-choosing-an-open-source-license
through to their domain at:
http://choosealicense.com/

**Comment by munificent** [comment]
Yeah, what's a little tricky is that I don't think I want the same license for the code and prose. I'm perfectly happy to completely open source all of the code, both the code that appears in the book and the scripts used to generate it. The JS too.

I'm less OK with allowing the prose to be modified and externally distributed, for reasons I can't fully articulate. Maybe because the prose is more my "voice" and feels more personal to me?

Likewise, I'd rather not have the CSS reused because I'd prefer other websites not look like a clone of this one.

Sorry I haven't sat down to sort this out yet.

**Comment by munificent** [comment]
OK, I took a stab at this. If I did this right, I picked a pair of licenses that should let people fork and contribute (which is so so awesome that people do!) while avoiding stuff like people selling their own ePub versions of it and things like that.

**Comment by tchalvak** [comment]
Nice.  The choices make sense to me, seems like you'll get what you're looking for with them.

**Comment by munificent** [comment]
\o/
