### ISSUE TITLE
Giving reference to the Evennia MUD server?

### ISSUE THREAD

**Issue by Griatch** [munificent/game-programming-patterns#359]
Hi @munificent, cool book. Looks like a very useful resource! 

I'm the lead developer/maintainer of [Evennia](https://github.com/evennia/evennia), a Python MUD creation library/server. 

One of our users recently made me aware of the prototype "goblin" examples from your book:
https://gameprogrammingpatterns.com/prototype.html#prototypes-for-data-modeling - 
These look like they were heavily inspired by the Evennia prototype example I wrote back in July of 2014:
https://github.com/evennia/evennia/blame/515ce71d65956ae3ef9c3e7be43e5673c8374436/game_template/world/prototypes.py

If so, that's cool and I take it as a compliment! A project like Evennia is niche enough that any exposure helps though. So if Evennia was an inspiration here, would it be possible to add a mention/link to it, like in the sidebar? I see this is done in other places of the book for other projects.

Cheers,
Griatch

**Comment by kovitikus** [comment]
I second this request. Evennia is a beautiful thing! It has helped me quickly learn Python in a most fun and awesome way. The community surrounding it is just as awesome!

**Comment by munificent** [comment]
The goblin example [has been in the book since fall of 2013](https://github.com/munificent/game-programming-patterns/commit/c67e4b540372d2c7118e61590769395cb59e8fb9). I don't know if the Evennia prototype was around then, but if so, I never read it. This is the first I've heard of Evennia. Unless you happened to see the chapter [when I posted it to Reddit](https://www.reddit.com/r/programming/comments/1ptsio/prototypes_design_pattern_language_paradigm_and/), it's probably just coincidence.

**Comment by Griatch** [comment]
@munificent Thanks for the answer! I was not on Reddit that far back, so it would appear this would be an example of a strange coincidence then. I guess when it comes to prototypes, goblins is a good example to go to. :)
